POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "SINCE THE CHANGES",
  "author": "J. K.Rowling",
  "url": "www.urltotheblog.com.au",
  "likes": 52,
  "userId": "65e7efcb4b3aa965dbdc74f9"
}
